### PR TITLE
Add: NGU

### PR DESCRIPTION
**Pull request by not-reed**

### CODE REVIEW

**Comment by Fugashu** [comment]
Thanks for the PR! I tried to build it locally, but the video isn't supported like thtat. It needs to be the sole .mp4 file for example, and not any links to players. 

I suggest to add it for now without the last entry in the json.

try 

``` 
"media": {
        "logoUrl": "/dapps/ngu/ngu-logo.png",
        "bannerUrl": "/dapps/ngu/ngu-banner.png",
        "previewUrl": "/dapps/ngu/ngu-preview.png"
    }
```

**Comment by not-reed** [comment]
@Fugashu I fixed the video link, sorry didn't try running it before. You should add a note in the instructions, I figured it required some .env variables or backend or something, so i didn't bother, but it worked good :fire: 
image

there was a bug if a video was supplied, but no gallery included, it crashed on the `((dappInfo.media?.gallery && dappInfo.media.gallery.length > 0) ||
        dappInfo.media.videoUrl) &&` condition in `src/pages/[name].tsx` but seems all good now :+1: let me know if theres things to be updated

**Comment by not-reed** [comment]
Also, I added the 'Trading' tag, not sure if that is supposed to be a strict enum, or if this is allowed, can remove if you would like 
image 
image

**Comment by not-reed** [comment]
image
added 'token' contract 

re: @larkben

**Comment by Fugashu** [comment]
Looking good now & thanks for the gallery fix! For the Trading Label, i will include it for now and also find a suitable logo to depict it on the left category section.

If the categories get too crazy tho, I might switch back at a later stage and just keep the "broad" categories.

image


I still need to do a bit of refactoring over the weekend. Will definitely enhance the description so it's more clear. In fact at build time it will fetch the data from our DB and statically generate those pages.

Cheers and welcome NGU to Alphadapps!

**Pull request merged**
